### ISSUE TITLE
integrate database

### ISSUE THREAD

**Issue by glebuben** [InnoSWP/B21-06-Seamless-support#7]

**Comment by glebuben** [comment]
I created two tables: Users, which consist of Users' cookies(in case person did not register), keyword(special word, which is unique for each User), volunteer_id(Id of a volunteer that is connected with this user); Questions which consist of questions and answers. Since backend part is not done yet, it is impossible to integrate db in our project

**Comment by glebuben** [comment]
For now everything is working. It will be added to the sprint 3

**Comment by RamPrin** [comment]
Done
